using System;
using System.Buffers.Binary;
using System.Numerics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Argon2Sharp.Core;
using Xunit;
using Xunit.Abstractions;

namespace Argon2Sharp.Tests
{
    public class CalculateBlockTest
    {
        private readonly ITestOutputHelper _output;

        public CalculateBlockTest(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public void CalculateB02()
        {
            // Parameters
            var password = new byte[32]; Array.Fill(password, (byte)0x01);
            var salt = new byte[16]; Array.Fill(salt, (byte)0x02);
            var secret = new byte[8]; Array.Fill(secret, (byte)0x03);
            var ad = new byte[12]; Array.Fill(ad, (byte)0x04);

            int parallelism = 4;
            int tagLength = 32;
            int memorySizeKB = 32;
            int iterations = 3;
            Argon2Version version = Argon2Version.Version13;
            Argon2Type type = Argon2Type.Argon2id;

            int memoryBlocks = memorySizeKB;
            int laneLength = memoryBlocks / parallelism;
            int segmentLength = laneLength / 4;

            // Allocate memory
            int totalQwords = memoryBlocks * 1024 / 8;
            var memory = new ulong[totalQwords];
            var memorySpan = new Span<ulong>(memory);

            // Initialize (H0 and first two blocks)
            Initialize(password, salt, secret, ad, parallelism, tagLength, memorySizeKB, iterations, version, type, memorySpan);

            // Output B[0][0] and B[0][1] for verification
            var b00 = GetBlock(memorySpan, 0, 0, laneLength);
            var b00Bytes = MemoryMarshal.AsBytes(b00);
            _output.WriteLine("B[0][0] first 8 bytes: " + Convert.ToHexString(b00Bytes.Slice(0, 8)));

            var b01 = GetBlock(memorySpan, 0, 1, laneLength);
            var b01Bytes = MemoryMarshal.AsBytes(b01);
            _output.WriteLine("B[0][1] first 8 bytes: " + Convert.ToHexString(b01Bytes.Slice(0, 8)));

            // We need to calculate B[0][2].
            // This is in Pass 0, Slice 0, Lane 0.
            // Index 2.
            
            int pass = 0;
            int slice = 0;
            int lane = 0;
            int index = 2; // Relative to slice start? No, relative to lane start.
            // In Slice 0, indices are 0 to segmentLength-1.
            // B[0][0] and B[0][1] are already filled.
            // We need B[0][2].
            
            // Check if B[0][2] is in Slice 0.
            // segmentLength = laneLength / 4.
            // laneLength = 32 / 4 = 8 blocks.
            // segmentLength = 8 / 4 = 2 blocks.
            // So Slice 0 contains blocks 0 and 1.
            // Slice 1 contains blocks 2 and 3.
            
            // Wait!
            // If segmentLength is 2, then Slice 0 has indices 0 and 1.
            // B[0][0] and B[0][1] are generated by Initialize.
            // So Slice 0 is fully filled by Initialize?
            // Let's check Argon2Engine.FillSegment.
            // int startIndex = (slice == 0 && pass == 0) ? 2 : 0;
            // for (int i = startIndex; i < _segmentLength; i++) ...
            
            // If segmentLength is 2, and startIndex is 2, the loop runs from 2 to 2 (i.e., never).
            // So FillSegment does NOTHING for Pass 0, Slice 0 if segmentLength is 2.
            
            // This implies B[0][2] is in Slice 1!
            // Slice 0: Blocks 0, 1.
            // Slice 1: Blocks 2, 3.
            
            // So B[0][2] is the first block of Slice 1.
            // Let's verify.
            // Lane 0, Index 2.
            // Slice 1 starts at index 2 * 1 = 2.
            // Yes.
            
            // So we need to calculate B[0][2] which is in Pass 0, Slice 1.
            // For Argon2id, Pass 0, Slice 1.
            // Is it data-independent?
            // Argon2Engine: bool dataIndependent = _isArgon2i || (_isArgon2id && pass == 0 && slice < 2);
            // slice < 2 means slice 0 and slice 1.
            // So yes, Slice 1 is data-independent.
            
            // So we need to run GenerateAddresses for Pass 0, Lane 0, Slice 1.
            
            slice = 1;
            index = 0; // First block of Slice 1 (which is absolute index 2 in lane)
            
            // Generate addresses for Slice 1
            int[] refLanes = new int[segmentLength];
            int[] refIndices = new int[segmentLength];
            GenerateAddresses(pass, lane, slice, memoryBlocks, iterations, type, segmentLength, parallelism, refLanes, refIndices);
            
            // Calculate B[0][2]
            // i = 0 (relative to slice)
            // Absolute index in lane = slice * segmentLength + i = 1 * 2 + 0 = 2.
            
            int currentOffset = lane * laneLength + slice * segmentLength + index; // 0 + 2 + 0 = 2
            int prevOffset = currentOffset - 1; // 1
            
            var b30 = GetBlock(memorySpan, 3, 0, laneLength);
            var b30Bytes = MemoryMarshal.AsBytes(b30);
            _output.WriteLine("B[3][0] first 8 bytes: " + Convert.ToHexString(b30Bytes.Slice(0, 8)));

            int refLane = refLanes[index];
            int refIndex = refIndices[index];
            _output.WriteLine($"RefLane: {refLane}, RefIndex: {refIndex}");
            int refOffset = refLane * laneLength + refIndex;
            
            var prevBlock = GetBlockByOffset(memorySpan, prevOffset);
            var refBlock = GetBlockByOffset(memorySpan, refOffset);
            var currentBlock = GetBlockByOffset(memorySpan, currentOffset);
            
            Argon2Core.FillBlock(prevBlock, refBlock, currentBlock, withXor: false);
            
            // Output first 32 bytes of currentBlock
            var bytes = new byte[32];
            var currentBlockBytes = MemoryMarshal.AsBytes(currentBlock);
            currentBlockBytes.Slice(0, 32).CopyTo(bytes);
            
            _output.WriteLine("B[0][2] first 32 bytes: " + Convert.ToHexString(bytes));
        }

        private void Initialize(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, ReadOnlySpan<byte> secret, ReadOnlySpan<byte> ad,
            int parallelism, int tagLength, int memorySizeKB, int iterations, Argon2Version version, Argon2Type type, Span<ulong> memory)
        {
            int h0Length = 40 + password.Length + salt.Length + secret.Length + ad.Length;
            Span<byte> h0Input = stackalloc byte[h0Length];
            int offset = 0;

            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), parallelism); offset += 4;
            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), tagLength); offset += 4;
            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), memorySizeKB); offset += 4;
            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), iterations); offset += 4;
            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), (int)version); offset += 4;
            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), (int)type); offset += 4;

            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), password.Length); offset += 4;
            password.CopyTo(h0Input.Slice(offset)); offset += password.Length;

            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), salt.Length); offset += 4;
            salt.CopyTo(h0Input.Slice(offset)); offset += salt.Length;

            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), secret.Length); offset += 4;
            secret.CopyTo(h0Input.Slice(offset)); offset += secret.Length;

            BinaryPrimitives.WriteInt32LittleEndian(h0Input.Slice(offset), ad.Length); offset += 4;
            ad.CopyTo(h0Input.Slice(offset));

            Span<byte> h0 = stackalloc byte[64];
            Blake2b.Hash(h0Input, h0);
            
            _output.WriteLine("H0: " + Convert.ToHexString(h0));

            Span<byte> blockBytes = stackalloc byte[1024];
            Span<byte> h0Extended = stackalloc byte[72];
            h0.CopyTo(h0Extended);

            int laneLength = memorySizeKB / parallelism;

            for (int lane = 0; lane < parallelism; lane++)
            {
                BinaryPrimitives.WriteInt32LittleEndian(h0Extended.Slice(64), 0);
                BinaryPrimitives.WriteInt32LittleEndian(h0Extended.Slice(68), lane);
                Blake2b.LongHash(h0Extended, blockBytes);
                Argon2Core.BytesToQwords(blockBytes, GetBlock(memory, lane, 0, laneLength));

                BinaryPrimitives.WriteInt32LittleEndian(h0Extended.Slice(64), 1);
                Blake2b.LongHash(h0Extended, blockBytes);
                Argon2Core.BytesToQwords(blockBytes, GetBlock(memory, lane, 1, laneLength));
            }
        }

        private void GenerateAddresses(int pass, int lane, int slice, int memoryBlocks, int iterations, Argon2Type type, int segmentLength, int parallelism, int[] refLanes, int[] refIndices)
        {
            int addressIterations = (segmentLength + 128 - 1) / 128;
            Span<ulong> inputBlock = stackalloc ulong[128];
            Span<ulong> z = stackalloc ulong[128];
            Span<ulong> zPrime = stackalloc ulong[128];

            for (int i = 0; i < addressIterations; i++)
            {
                inputBlock.Clear();
                inputBlock[0] = (ulong)pass;
                inputBlock[1] = (ulong)lane;
                inputBlock[2] = (ulong)slice;
                inputBlock[3] = (ulong)memoryBlocks;
                inputBlock[4] = (ulong)iterations;
                inputBlock[5] = (ulong)type;
                inputBlock[6] = (ulong)(i + 1);
                inputBlock[7] = 0;

                inputBlock.CopyTo(z);
                Argon2Core.PermutationP(z);
                // XorBlock
                for(int k=0; k<128; k++) z[k] ^= inputBlock[k];

                z.CopyTo(zPrime);
                Argon2Core.PermutationP(zPrime);
                // XorBlock
                for(int k=0; k<128; k++) zPrime[k] ^= z[k];

                for (int j = 0; j < 128; j++)
                {
                    int index = i * 128 + j;
                    if (index >= segmentLength) break;

                    ulong v = zPrime[j];
                    uint j1 = (uint)v;
                    uint j2 = (uint)(v >> 32);

                    ComputeReferenceLocation(pass, lane, slice, index, j1, j2, parallelism, segmentLength, memoryBlocks / parallelism, out int refLane, out int refIndex);
                    refLanes[index] = refLane;
                    refIndices[index] = refIndex;
                }
            }
        }

        private void ComputeReferenceLocation(int pass, int lane, int slice, int index, uint j1, uint j2, int parallelism, int segmentLength, int laneLength, out int refLane, out int refIndex)
        {
            refLane = (int)(j2 % (uint)parallelism);
            if (pass == 0 && slice == 0) refLane = lane;
            bool sameLane = refLane == lane;

            int referenceAreaSize;
            int startPosition;

            if (pass == 0)
            {
                startPosition = 0;
                if (slice == 0)
                {
                    referenceAreaSize = index - 1;
                }
                else
                {
                    referenceAreaSize = sameLane
                        ? (slice * segmentLength + index - 1)
                        : (slice * segmentLength);
                }
            }
            else
            {
                startPosition = ((slice + 1) * segmentLength) % laneLength;
                referenceAreaSize = sameLane
                    ? (laneLength - segmentLength + index - 1)
                    : (laneLength - segmentLength);
            }

            if (!sameLane && index == 0)
            {
                referenceAreaSize--;
            }

            if (referenceAreaSize < 1)
            {
                refIndex = 0;
                return;
            }

            ulong relativePosition = j1;
            relativePosition = (relativePosition * relativePosition) >> 32;
            relativePosition = (ulong)referenceAreaSize - 1 - ((ulong)referenceAreaSize * relativePosition >> 32);

            refIndex = (startPosition + (int)relativePosition) % laneLength;
        }

        private Span<ulong> GetBlock(Span<ulong> memory, int lane, int index, int laneLength)
        {
            return memory.Slice((lane * laneLength + index) * 128, 128);
        }

        private Span<ulong> GetBlockByOffset(Span<ulong> memory, int offset)
        {
            return memory.Slice(offset * 128, 128);
        }
    }
}
